
# C++ source files
CSRC += src/key.c
CSRC += src/main.c
CSRC += src/test.c
CSRC += src/vmode.c

CSRC += img/img640x600x1.c
CSRC += img/img640x300x2bw.c
CSRC += img/img640x300x2col1.c
CSRC += img/img640x300x2col2.c
CSRC += img/img320x300x4bw.c
CSRC += img/img320x300x4col.c
CSRC += img/img320x150x8.c
CSRC += img/img160x300x8.c
CSRC += img/img160x150x16.c

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
